name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sqlalchemy=1.4
  - pip
  - pip:
      - hummingbot
      - numpy==1.26.4
      - streamlit==1.41.1
      - watchdog
      - python-dotenv
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - pathlib
      - st_pages
      - st-pages==0.5.0
      - streamlit-elements==0.1.*
      - streamlit-authenticator==0.4.1
      - pydantic==1.10.4
      - flake8
      - isort
      - pre-commit
      - optuna
      - optuna-dashboard
      - sqlalchemy.orm
