name: Dashboard Conda

on: 
  push:
    branches:
      - develop

jobs:

  install-dependencies:
    needs: install-miniconda
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create or Update Conda Environment
        run: |
          conda env update -f environment_conda.yml -n dashboard --prune
      - name: List Conda Environments
        run: conda env list

  init-conda:
    needs: install-dependencies
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Conda
        run: |
          conda init bash

  activate-conda:
    needs: [init-conda]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Get Conda Info
        run: |
          conda info
      - name: Activate Conda environment
        shell: bash
        run: |
          conda activate dashboard || echo "Failed to activate environment, continuing anyway"

  run-dashboard:
    needs: [activate-conda, install-dependencies]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Verify Environment Before Running
        run: conda env list

      - name: Run Streamlit Dashboard
        run: |
          streamlit run main.py --server.headless true || echo "Streamlit execution failed with exit code $?"
