name: Dashboard Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

  install-miniconda:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.10'
      - name: Verify Miniconda Installation
        run: |
          conda --version
          which conda
          conda info

  install-dependencies:
    needs: install-miniconda
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Create Conda Environment
        run: conda env create -f environment_conda.yml -n dashboard
      - name: List Conda Environments
        run: conda env list

  init-conda:
    needs: install-dependencies  # This job initializes Conda, which should happen after dependencies are installed
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Conda
        run: |
          conda init bash

  activate-conda:
    needs: [init-conda]  # Only needs init-conda, not install-miniconda directly
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Get Conda Info
        run: |
          conda info
      - name: Activate Conda environment
        shell: bash
        run: |
          source $(dirname $(which conda))/../etc/profile.d/conda.sh
          conda activate dashboard || echo "Failed to activate environment, continuing anyway"

  run-dashboard:
    needs: activate-conda
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify Environment Before Running
        run: conda env list
      - name: Check Conda Configuration
        run: |
          conda config --show-sources
          ls -la /usr/share/miniconda/envs
      - name: Check Environment Directory Permissions
        run: |
          ls -la /usr/share/miniconda/envs
          ls -la /usr/share/miniconda/envs/dashboard
      - name: Run Streamlit Dashboard
        run: |
          conda run -n dashboard --no-capture-output streamlit run main.py --server.headless true || echo "Streamlit execution failed with exit code $?"
